---
on:  # yamllint disable-line rule:truthy
  release:
    types:
      - published

jobs:
  deploy_to_edge_net:
    name: Update Raindrops
    runs-on: ubuntu-latest
    steps:
      - name: Get aws-commander
        run: |
          wget https://github.com/Trapesys/aws-commander/releases/download/v0.2.0/aws-commander_0.2.0_Linux_x86_64.tar.gz
          tar -xf aws-commander_0.2.0_Linux_x86_64.tar.gz
          sudo mv aws-commander /usr/local/bin

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment Ansible
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.RAINDROPS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RAINDROPS_AWS_SECRET_ACCESS_KEY }}
        run: >
          /usr/local/bin/aws-commander
          -instances i-xxxxxxxxx,i-xxxxxxxxx,i-xxxxxxxxx,i-xxxxxxxxx
          -mode ansible
          -playbook .github/workflows/ansible/update_edgenet.yaml
          -aws-zone us-west-2
